### ISSUE TITLE
Version 0.1.1 is not in the repository?

### ISSUE THREAD

**Issue by mvz** [samueldana/indentation#1]
Hi, it seems version 0.1.1 of this gem is out, but the repo is stuck at 0.0.7. Would you mind pushing the code for 0.1.1?

**Comment by samueldana** [comment]
My mistake. Thanks for the notification, I'll update it on Monday.

On Sun, Apr 5, 2015 at 2:39 AM, Matijs van Zuijlen <notifications@github.com

**Comment by mvz** [comment]
Thanks!
